(cl:defpackage scout_msgs-msg
  (:use )
  (:export
   "<SCOUTDRIVERSTATE>"
   "SCOUTDRIVERSTATE"
   "<SCOUTLIGHTCMD>"
   "SCOUTLIGHTCMD"
   "<SCOUTLIGHTSTATE>"
   "SCOUTLIGHTSTATE"
   "<SCOUTMOTORSTATE>"
   "SCOUTMOTORSTATE"
   "<SCOUTSTATUS>"
   "SCOUTSTATUS"
  ))

